"""Core module exports."""

from voice_agent.core.constants import (
    CHUNK_DURATION_MS,
    DEFAULT_ASR_MODEL,
    DEFAULT_LLM_MODEL,
    DEFAULT_TTS_MODEL,
    GROQ_BASE_URL,
    MAX_AUDIO_BUFFER_MS,
    SAMPLE_RATE,
    TARGET_ASR_LATENCY_MS,
    TARGET_E2E_LATENCY_MS,
    TARGET_TTS_LATENCY_MS,
    TARGET_TTFA_MS,
    TARGET_VAD_LATENCY_MS,
    VAD_MIN_SILENCE_MS,
    VAD_MIN_SPEECH_MS,
    VAD_THRESHOLD,
)
from voice_agent.core.exceptions import (
    ASRError,
    AudioError,
    ConfigError,
    LLMError,
    PipelineError,
    ServiceError,
    TTSError,
    VADError,
    VoiceAgentError,
)
from voice_agent.core.types import (
    ASRConfig,
    AudioConfig,
    AudioFormat,
    IASRService,
    IAudioProcessor,
    ILLMService,
    ITTSService,
    IVADService,
    LLMConfig,
    PipelineMetrics,
    PipelineState,
    SynthesisResult,
    TranscriptionResult,
    TTSConfig,
    VADConfig,
    VADResult,
)

__all__ = [
    # Constants
    "SAMPLE_RATE",
    "CHUNK_DURATION_MS",
    "MAX_AUDIO_BUFFER_MS",
    "VAD_THRESHOLD",
    "VAD_MIN_SPEECH_MS",
    "VAD_MIN_SILENCE_MS",
    "TARGET_VAD_LATENCY_MS",
    "TARGET_ASR_LATENCY_MS",
    "TARGET_TTS_LATENCY_MS",
    "TARGET_TTFA_MS",
    "TARGET_E2E_LATENCY_MS",
    "DEFAULT_ASR_MODEL",
    "DEFAULT_TTS_MODEL",
    "DEFAULT_LLM_MODEL",
    "GROQ_BASE_URL",
    # Exceptions
    "VoiceAgentError",
    "ServiceError",
    "VADError",
    "ASRError",
    "TTSError",
    "LLMError",
    "PipelineError",
    "AudioError",
    "ConfigError",
    # Types
    "AudioConfig",
    "AudioFormat",
    "VADConfig",
    "ASRConfig",
    "TTSConfig",
    "LLMConfig",
    "VADResult",
    "TranscriptionResult",
    "SynthesisResult",
    "PipelineMetrics",
    "PipelineState",
    # Protocols
    "IAudioProcessor",
    "IVADService",
    "IASRService",
    "ITTSService",
    "ILLMService",
]
